#ifndef __TEST_SETTINGS__
#define __TEST_SETTINGS__

#define LIGHT_DATA_SEQUENTIAL_ARRAY_SIZE 1000000
#define LIGHT_DATA_SEQUENTIAL_TEST_COUNT 100

#define LIGHT_DATA_RANDOM_ARRAY_SIZE 100000
#define LIGHT_DATA_RANDOM_TEST_COUNT 5

#define MEDIUM_DATA_SEQUENTIAL_ARRAY_SIZE 1000000
#define MEDIUM_DATA_SEQUENTIAL_TEST_COUNT 100

#define MEDIUM_DATA_RANDOM_ARRAY_SIZE 100000
#define MEDIUM_DATA_RANDOM_TEST_COUNT 5

#define BIG_DATA_SEQUENTIAL_ARRAY_SIZE 500000
#define BIG_DATA_SEQUENTIAL_TEST_COUNT 100

#define BIG_DATA_RANDOM_ARRAY_SIZE 100000
#define BIG_DATA_RANDOM_TEST_COUNT 5


#endif // __TEST_SETTINGS__